Attaching to amfxprisma_prisma_1
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5000ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5002ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5003ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5002ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5003ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5009ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5009ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5007ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5006ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5002ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5005ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5007ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[36mprisma_1  |[0m 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
[36mprisma_1  |[0m 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[36mprisma_1  |[0m 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36mprisma_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36mprisma_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36mprisma_1  |[0m Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=host.docker.internal)(port=3306)(type=master) : host.docker.internal
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
[36mprisma_1  |[0m 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
[36mprisma_1  |[0m 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
[36mprisma_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mprisma_1  |[0m 	... 3 more
[36mprisma_1  |[0m Caused by: java.net.UnknownHostException: host.docker.internal
[36mprisma_1  |[0m 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[36mprisma_1  |[0m 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:589)
[36mprisma_1  |[0m 	at java.net.Socket.connect(Socket.java:538)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
[36mprisma_1  |[0m 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
[36mprisma_1  |[0m 	... 14 more
[36mprisma_1  |[0m No log level set, defaulting to INFO.
[36mprisma_1  |[0m [INFO] {} - Started.
[36mprisma_1  |[0m [INFO] {} - Started.
